# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CBOperationsDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CBOperationsDemo
  pod 'couchbase-lite-ios'
  pod 'UITextField+Blocks'
  pod 'JVFloatLabeledTextField'
  pod 'IQKeyboardManagerSwift'

end

